export default function Head() {
  return (
    <>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta
        name="keywords"
        content="Creative Website, Personal Portfolio, Personal Website, Aditya Shah"
      ></meta>
      <meta
        name="description"
        content="Personal Website Of Aditya Shah Where You Can Find His Works And About Him"
      ></meta>
      <meta name="copyright" content="Aditya Shah - ewwadii.com" />
      <meta name="language" content="EN" />
      <meta name="robots" content="index,follow" />
      <meta name="revised" content="Sunday, July 18th, 2023, 5:15 pm" />
      <meta name="abstract" content="" />
      <meta name="topic" content="Personal Website" />
      <meta name="summary" content="" />
      <meta name="Classification" content="Business" />
      <meta name="author" content="Aditya Shah, business@ewwadii.com" />
      <meta name="designer" content="" />
      <meta name="reply-to" content="business@ewwadii.com" />
      <meta name="owner" content="" />
      <meta name="url" content="http://ewwadii.com" />
      <meta name="identifier-URL" content="http://ewwadii.com" />
      <meta name="directory" content="submission" />
      <meta name="category" content="Personal Website" />
      <meta name="coverage" content="Worldwide" />
      <meta name="distribution" content="Global" />
      <meta name="rating" content="General" />
      <meta name="revisit-after" content="7 days" />
      <meta name="subtitle" content="Aditya Shah Front-End Web Developer" />
      <meta name="target" content="all" />
      <meta name="HandheldFriendly" content="True" />
      <meta name="MobileOptimized" content="320" />
      <meta name="date" content="Jan, 20, 2023" />
      <meta name="search_date" content="2023-1-19" />
      <meta name="ResourceLoaderDynamicStyles" content="" />
      <meta name="medium" content="work" />
      <meta name="syndication-source" content="https://ewwadii.com" />
      <meta name="original-source" content="https://ewwadii.com" />
      {/* <meta
          name="verify-v1"
          content="dV1r/ZJJdDEI++fKJ6iDEl6o+TMNtSu0kv18ONeqM0I="
        ></meta>
        <meta name="y_key" content="1e39c508e0d87750"></meta> */}
      <meta name="pageKey" content="guest-home" />
      <meta http-equiv="Expires" content="0" />
      <meta http-equiv="Pragma" content="no-cache" />
      <meta http-equiv="Cache-Control" content="no-cache" />
      <meta http-equiv="imagetoolbar" content="no" />
      <meta http-equiv="x-dns-prefetch-control" content="off" />
      <meta name="og:title" content="Aditya Shah" />
      <meta name="og:type" content="Personal Website" />
      <meta name="og:url" content="https://ewwadii.com" />
      <meta name="og:image" content="none" />
      <meta name="og:site_name" content="Aditya Shah" />
      <meta
        name="og:description"
        content="Personal Website Of Aditya Shah Where You Can Find His Works And About Him"
      />

      <meta name="fb:page_id" content="7564686" />
      <meta name="application-name" content="foursquare" />
      <meta name="og:email" content="business@ewwadii.com" />
      <meta name="og:phone_number" content="none" />
      <meta name="og:fax_number" content="none" />

      <meta name="og:latitude" content="none" />
      <meta name="og:longitude" content="none" />
      <meta name="og:street-address" content="Ballarpur Shivaji Ward" />
      <meta name="og:locality" content="Chandrapur" />
      <meta name="og:region" content="MH" />
      <meta name="og:postal-code" content="442701" />
      <meta name="og:country-name" content="INDIA" />
      <meta property="fb:admins" content="2" />
    </>
  );
}
